# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=256)),
                ('latest_end_date', models.DateTimeField()),
                ('earliest_start_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Committee')),
                ('op_managers', models.ManyToManyField(blank=True, to='people.Manager')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
            ],
            options={
                'verbose_name': 'Program Type',
                'verbose_name_plural': 'Program Types',
            },
        ),
        migrations.AddField(
            model_name='opportunity',
            name='program_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities.ProgramType'),
        ),
    ]
