# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0002_opportunity_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='committee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Committee'),
        ),
    ]
