# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities', '0004_auto_20171109_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='op_managers',
            field=models.ManyToManyField(to='people.Manager'),
        ),
    ]
