# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apirequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
