# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('current_page', models.IntegerField()),
                ('total_pages', models.IntegerField()),
            ],
            options={
                'verbose_name': 'API Request',
                'verbose_name_plural': 'API Requests',
            },
        ),
        migrations.AlterModelOptions(
            name='accesstoken',
            options={'verbose_name': 'Access Token', 'verbose_name_plural': 'Access Token'},
        ),
    ]
