# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171026_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='apirequest',
            name='type',
            field=models.CharField(choices=[(1, 'Applications'), (2, 'Opportunities'), (9, 'None')], default=9, max_length=1),
        ),
    ]
