# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171023_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='current_page',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='apirequest',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
    ]
