# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-26 07:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_apirequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequest',
            name='type',
            field=models.IntegerField(choices=[(1, 'Applications'), (2, 'Opportunities'), (9, 'None')], default=9),
        ),
    ]
