# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_approved', models.DateTimeField(blank=True, null=True)),
                ('date_realized', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(max_length=256)),
                ('experience_start_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('exchange_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people.ExchangeParticipant')),
            ],
        ),
    ]
