# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
