# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 17:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_an_signed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
