# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-09 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_auto_20171107_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='date_accepted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_ep_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_matched',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_tn_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='date_withdrawn',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='experience_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_an_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_ep_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_matched',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_tn_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='state_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='status_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='status_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timeline',
            name='status_realized',
            field=models.BooleanField(default=False),
        ),
    ]
