# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-23 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangeparticipant',
            name='committee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Committee'),
        ),
    ]
