# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-04 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0002_auto_20171104_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangeparticipant',
            options={'verbose_name': 'Exchange Participant', 'verbose_name_plural': 'Exchange Participants'},
        ),
        migrations.AlterModelOptions(
            name='manager',
            options={'verbose_name': 'Manager', 'verbose_name_plural': 'Managers'},
        ),
    ]
