# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0003_auto_20171104_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchangeparticipant',
            name='updated',
            field=models.BooleanField(default=False),
        ),
    ]
