# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-22 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expa_id',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
