# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-25 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_expa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='expa_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
